### ISSUE TITLE
Return integer values

### ISSUE THREAD

**Issue by cstepper** [jojo-/mipfp#1]
Hi,

just out of curiosity:

Would it be possible to return integer values after running the IPFP while keeping the marginal sum restrictions?

In our usecase, we need to round modelled population figures, and in our result we want to have "number of persons".

Cheers, Christoph

**Comment by jojo-** [comment]
Hi,

Yes, no worries. You simply need to round the elements in $hat.

For instance if the result of Ipfp is stored in res, then simply use round(res$hat).

There are better ways to round the outputs from the Ipfp procedure, see for instance this paper: https://www.sciencedirect.com/science/article/pii/S0198971513000240?via%3Dihub

Cheers,

Johan

________________________________
De : Christoph Stepper <notifications@github.com>
Envoyé : mercredi 15 mai 2019 18:12
À : jojo-/mipfp
Cc : Subscribed
Objet : [jojo-/mipfp] Return integer values (#1)


Hi,

just out of curiosity:

Would it be possible to return integer values after running the IPFP while keeping the marginal sum restrictions?

In our usecase, we need to round modelled population figures, and in our result we want to have "number of persons".

Cheers, Christoph

**Comment by cstepper** [comment]
Hi Johan,

thanks for your answer, 
we'll have a look at that paper.

Best, Christoph
